name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Show Flutter & Java version
        run: |
          flutter --version
          java -version

      - name: Flutter doctor (verbose)
        run: flutter doctor -v || true

      - name: Print env (for Android SDK vars)
        run: env | grep -i ANDROID || true

      - name: Flutter pub get
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests (verbose)
        run: flutter test --reporter=expanded

      - name: Build debug APK (only if previous steps success)
        if: success()
        run: flutter build apk --debug --no-shrink -v

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk